### ISSUE TITLE
permissions issue when using sbt/setup-sbt

### ISSUE THREAD

**Issue by pjfanning** [sbt/setup-sbt#2]
I updated one of my projects due to a PR from Scala Steward that highlighted the new release of sbt-github-actions.
This update added this action to my CI build yml.

GitHub CI won't now allow the CI jobs to run.

https://github.com/pjfanning/micrometer-pekko/actions/runs/9652616894/workflow
```
sbt/setup-sbt@v1 is not allowed to be used in pjfanning/micrometer-pekko. Actions in this workflow must be: within a repository owned by pjfanning, created by GitHub, or verified in the GitHub Marketplace.
```

Any ideas why GitHub CI is suspicious about this action?

Could there be a name clash with https://github.com/marketplace/actions/setup-sbt ?

**Comment by eed3si9n** [comment]
Thanks for the report! Yea I guess I need to pick some other name.

**Comment by pjfanning** [comment]
Oddly, I upgraded another of my projects so that it now uses this action and that project continues to build ok.
https://github.com/swagger-akka-http/swagger-scala-module

I'm sure why there are issues reported for https://github.com/pjfanning/micrometer-pekko
I will try to rerun the build there.

**Comment by eed3si9n** [comment]
Per @laughedelic's advice I've re-enabled this repo and registered this as https://github.com/marketplace/actions/setup-sbt-installer instead.
